service: pct-backend

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:DEPLOYMENT_STAGE}
  region: ap-southeast-2

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"