service: pct-backend
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
  memorySize: 128
  versionFunctions: false

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    noPrependStageInUrl: true

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  app:
    handler: src/index.handler
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_NAME: ${env:DB_NAME}
      DB_PASSWORD: ${env:DB_PASSWORD}
      DB_USERNAME: ${env:DB_USERNAME}
      CORS_SITE: ${env:CORS_SITE, ""}
    events:
      - http:
          path: /
          method: ANY
          cors: true

      - http:
          path: "{proxy+}"
          method: ANY
          cors: true