service: pct-backend
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${env:DEPLOYMENT_STAGE}
  region: ap-southeast-2
  vpc:
    securityGroupIds:
      - sg-098a329c55b23281c
    subnetIds:
      - subnet-fb1cd49d

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    noPrependStageInUrl: true

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY

      - http:
          path: "{proxy+}"
          method: ANY