service: pct-backend

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:DEPLOYMENT_STAGE}
  region: ap-southeast-2
  vpc:
    securityGroupIds:
      - sg-098a329c55b23281c
    subnetIds:
      - subnet-fb1cd49d

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
          origins:
            - http://*.pingchengtech.com
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
          allowCredentials: false

      - http:
          path: "{proxy+}"
          method: ANY
          origins:
            - http://*.pingchengtech.com
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
          allowCredentials: false